import type { Job } from './types'

export const JOB_CATALOG: Job[] = [
  {
    id: 'abc-fullstack',
    source: 'greenhouse',
    sourceJobId: 'abc-sfe',
    title: 'Senior Full Stack Engineer',
    company: 'ABC Technologies',
    description:
      'Senior Full Stack Engineer. Requirements: 5+ years experience, React, Next.js, TypeScript, Node.js, PostgreSQL. Preferred: AWS, Docker. Remote, full-time. Build product features across the stack and ship with a small team.',
    location: 'Remote worldwide',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 120000,
    salaryMax: 160000,
    currency: 'USD',
    skills: ['React', 'Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS', 'Docker'],
    requiredExperience: 5,
    seniority: 'senior',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Senior%20Full%20Stack%20Engineer%20ABC%20Technologies',
    applyChannel: 'Open listing — submit on official boards',
    postedAt: '2026-09-06',
  },
  {
    id: 'li-abc-dup',
    source: 'linkedin',
    sourceJobId: 'li-abc',
    title: 'Sr Full-Stack Engineer',
    company: 'ABC Technologies',
    description: 'Same Senior Full Stack role syndicated on LinkedIn. React, Next.js, TypeScript, Node.js, PostgreSQL. Remote.',
    location: 'Remote',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 118000,
    salaryMax: 158000,
    currency: 'USD',
    skills: ['React', 'Next.js', 'TypeScript', 'Node.js', 'PostgreSQL'],
    seniority: 'senior',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Sr%20Full-Stack%20Engineer%20ABC%20Technologies',
    applyChannel: 'Open listing — submit materials yourself',
    postedAt: '2026-09-07',
  },
  {
    id: 'ind-abc-dup',
    source: 'indeed',
    sourceJobId: 'ind-abc',
    title: 'Senior Full Stack Developer',
    company: 'ABC Technologies',
    description: 'Indeed copy of ABC Technologies full stack role.',
    location: 'Remote',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 120000,
    salaryMax: 160000,
    currency: 'USD',
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
    seniority: 'senior',
    applicationUrl: 'https://www.indeed.com/jobs?q=Senior%20Full%20Stack%20Developer%20ABC%20Technologies',
    applyChannel: 'Open listing — submit materials yourself',
    postedAt: '2026-09-07',
  },
  {
    id: 'ai-auto',
    source: 'feed',
    title: 'AI Automation Engineer',
    company: 'Northwind Labs',
    description:
      'Build AI agents and automations with OpenAI, n8n, RAG, TypeScript, and Node.js. 4+ years. Remote. Contract or full-time.',
    location: 'Remote',
    remote: true,
    workMode: 'remote',
    employmentType: 'contract',
    salaryMin: 110000,
    salaryMax: 150000,
    currency: 'USD',
    skills: ['TypeScript', 'Node.js', 'OpenAI', 'AI Agents', 'RAG', 'n8n', 'Python'],
    requiredExperience: 4,
    seniority: 'senior',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=AI%20Automation%20Engineer%20Northwind%20Labs',
    applyChannel: 'Ashby (authorized portal)',
    postedAt: '2026-09-05',
  },
  {
    id: 'react-eng',
    source: 'lever',
    title: 'React Engineer',
    company: 'Harbor Pay',
    description:
      'Product React engineer. TypeScript, Next.js, Node.js. Hybrid Philippines or remote. Full-time.',
    location: 'Manila, Philippines (Hybrid) / Remote',
    remote: true,
    workMode: 'hybrid',
    employmentType: 'full-time',
    salaryMin: 72000,
    salaryMax: 110000,
    currency: 'USD',
    skills: ['React', 'TypeScript', 'Next.js', 'Node.js', 'CSS'],
    requiredExperience: 3,
    seniority: 'mid',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=React%20HarborPay',
    applyChannel: 'Lever (authorized portal)',
    postedAt: '2026-09-04',
  },
  {
    id: 'gh-stripe-fe',
    source: 'greenhouse',
    title: 'Senior Frontend Engineer, Dashboard',
    company: 'Stripe',
    description:
      'Build the Stripe Dashboard in TypeScript and React. Design systems, accessibility, performance. Hybrid SF. Full-time.',
    location: 'San Francisco, CA',
    remote: false,
    workMode: 'hybrid',
    employmentType: 'full-time',
    salaryMin: 195000,
    salaryMax: 265000,
    currency: 'USD',
    skills: ['TypeScript', 'React', 'CSS', 'System Design'],
    requiredExperience: 6,
    seniority: 'senior',
    applicationUrl: 'https://stripe.com/jobs/listing/senior-frontend-engineer',
    applyChannel: 'Greenhouse (authorized portal)',
    postedAt: '2026-09-02',
  },
  {
    id: 'cp-github-fe',
    source: 'career_page',
    title: 'Senior Web Engineer, Primer',
    company: 'GitHub',
    description: 'Primer design system. React, TypeScript, accessibility. Remote US. Full-time.',
    location: 'Remote (US)',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 170000,
    salaryMax: 235000,
    currency: 'USD',
    skills: ['React', 'TypeScript', 'CSS', 'Accessibility'],
    seniority: 'senior',
    applicationUrl: 'https://github.com/about/careers',
    applyChannel: 'Greenhouse (authorized portal)',
    postedAt: '2026-08-29',
  },
  {
    id: 'gh-github-dup',
    source: 'linkedin',
    title: 'Sr Web Engineer (Primer Design System)',
    company: 'GitHub',
    description: 'LinkedIn syndication of Primer role.',
    location: 'United States — Remote',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 168000,
    salaryMax: 232000,
    currency: 'USD',
    skills: ['React', 'TypeScript', 'Accessibility'],
    seniority: 'senior',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=GitHub',
    applyChannel: 'Open listing — submit materials yourself',
    postedAt: '2026-08-29',
  },
  {
    id: 'feed-vercel-dx',
    source: 'api',
    title: 'Senior Engineer, Developer Experience',
    company: 'Vercel',
    description: 'Next.js and Vercel dashboard. TypeScript, React, Node.js. Remote Americas. Full-time.',
    location: 'Remote (Americas)',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 175000,
    salaryMax: 240000,
    currency: 'USD',
    skills: ['TypeScript', 'React', 'Next.js', 'Node.js', 'Vite'],
    seniority: 'senior',
    applicationUrl: 'https://vercel.com/careers',
    applyChannel: 'Greenhouse (authorized portal)',
    postedAt: '2026-08-30',
  },
  {
    id: 'ramp-fe',
    source: 'feed',
    title: 'Senior Frontend Engineer, Spend',
    company: 'Ramp',
    description: 'Finance product UI. React, TypeScript, GraphQL. Remote. Full-time.',
    location: 'Remote',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 185000,
    salaryMax: 245000,
    currency: 'USD',
    skills: ['React', 'TypeScript', 'GraphQL'],
    seniority: 'senior',
    applicationUrl: 'https://ramp.com/careers',
    applyChannel: 'Ashby (authorized portal)',
    postedAt: '2026-09-05',
  },
  {
    id: 'shopify-fe',
    source: 'linkedin',
    title: 'Senior Frontend Developer, Hydrogen',
    company: 'Shopify',
    description: 'Hydrogen storefronts. React, TypeScript, GraphQL. Remote Americas. Full-time.',
    location: 'Remote (Americas)',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 160000,
    salaryMax: 220000,
    currency: 'USD',
    skills: ['React', 'TypeScript', 'GraphQL', 'Node.js'],
    seniority: 'senior',
    applicationUrl: 'https://www.shopify.com/careers',
    applyChannel: 'Open listing — submit materials yourself',
    postedAt: '2026-08-25',
  },
  {
    id: 'linear-fe',
    source: 'indeed',
    title: 'Senior Frontend Engineer',
    company: 'Linear',
    description: 'High-craft React/TypeScript. Remote US. Full-time.',
    location: 'Remote (US)',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 180000,
    salaryMax: 230000,
    currency: 'USD',
    skills: ['React', 'TypeScript', 'CSS'],
    seniority: 'senior',
    applicationUrl: 'https://linear.app/careers',
    applyChannel: 'Ashby (authorized portal)',
    postedAt: '2026-09-04',
  },
  {
    id: 'databricks-be',
    source: 'indeed',
    title: 'Staff Backend Engineer, Control Plane',
    company: 'Databricks',
    description: 'Java, Kotlin, Kubernetes, Terraform. Not a frontend role. Hybrid Mountain View.',
    location: 'Mountain View, CA',
    remote: false,
    workMode: 'hybrid',
    employmentType: 'full-time',
    salaryMin: 230000,
    salaryMax: 320000,
    currency: 'USD',
    skills: ['Java', 'Kotlin', 'Kubernetes', 'Terraform', 'AWS'],
    seniority: 'lead',
    applicationUrl: 'https://www.databricks.com/company/careers',
    applyChannel: 'Greenhouse (authorized portal)',
    postedAt: '2026-09-03',
  },
  {
    id: 'java-bank',
    source: 'career_page',
    title: 'Java Platform Engineer',
    company: 'Northstar Bank',
    description: 'Core banking Java. Onsite New York. SQL and Linux. No frontend.',
    location: 'New York, NY',
    remote: false,
    workMode: 'onsite',
    employmentType: 'full-time',
    salaryMin: 145000,
    salaryMax: 175000,
    currency: 'USD',
    skills: ['Java', 'SQL', 'Linux'],
    seniority: 'mid',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Java%20Northstar%20Bank',
    applyChannel: 'Workday (authorized portal)',
    postedAt: '2026-09-06',
  },
  {
    id: 'sales-ae',
    source: 'feed',
    title: 'Enterprise Account Executive',
    company: 'Cloudspan',
    description: 'Quota-carrying enterprise sales. Not a software role.',
    location: 'Austin, TX',
    remote: false,
    workMode: 'hybrid',
    employmentType: 'full-time',
    salaryMin: 120000,
    salaryMax: 250000,
    currency: 'USD',
    skills: ['Communication', 'Leadership'],
    seniority: 'senior',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Cloudspan',
    applyChannel: 'Greenhouse (authorized portal)',
    postedAt: '2026-09-04',
  },
  {
    id: 'intern-fe',
    source: 'linkedin',
    title: 'Frontend Engineering Intern',
    company: 'Brightloop',
    description: 'Summer internship. Learn React. Not a senior role.',
    location: 'San Francisco, CA',
    remote: false,
    workMode: 'hybrid',
    employmentType: 'full-time',
    salaryMin: 40000,
    salaryMax: 55000,
    currency: 'USD',
    skills: ['JavaScript', 'HTML', 'CSS', 'React'],
    seniority: 'junior',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Brightloop',
    applyChannel: 'Lever (authorized portal)',
    postedAt: '2026-09-06',
  },
  {
    id: 'plaid-em',
    source: 'career_page',
    title: 'Engineering Manager, Frontend',
    company: 'Plaid',
    description: 'People-manager for a frontend team of 8. Hiring and performance, limited IC work.',
    location: 'San Francisco, CA',
    remote: false,
    workMode: 'hybrid',
    employmentType: 'full-time',
    salaryMin: 210000,
    salaryMax: 280000,
    currency: 'USD',
    skills: ['Leadership', 'Mentoring', 'React', 'Communication'],
    seniority: 'manager',
    applicationUrl: 'https://plaid.com/careers/em-frontend',
    applyChannel: 'Greenhouse (authorized portal)',
    postedAt: '2026-08-27',
  },
  {
    id: 'cloudflare-fe',
    source: 'greenhouse',
    title: 'Senior Frontend Engineer, Dashboard',
    company: 'Cloudflare',
    description: 'Complex React dashboard. TypeScript, REST APIs. Remote US. Full-time.',
    location: 'Remote (US)',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 170000,
    salaryMax: 230000,
    currency: 'USD',
    skills: ['React', 'TypeScript', 'REST APIs'],
    seniority: 'senior',
    applicationUrl: 'https://www.cloudflare.com/careers',
    applyChannel: 'Greenhouse (authorized portal)',
    postedAt: '2026-09-01',
  },
  {
    id: 'notion-web',
    source: 'career_page',
    title: 'Senior Software Engineer, Web',
    company: 'Notion',
    description: 'Notion web client. React, TypeScript, Next.js. Hybrid SF. Full-time.',
    location: 'San Francisco, CA',
    remote: false,
    workMode: 'hybrid',
    employmentType: 'full-time',
    salaryMin: 185000,
    salaryMax: 250000,
    currency: 'USD',
    skills: ['React', 'TypeScript', 'JavaScript', 'Next.js'],
    seniority: 'senior',
    applicationUrl: 'https://www.notion.so/careers',
    applyChannel: 'Greenhouse (authorized portal)',
    postedAt: '2026-09-01',
  },
  {
    id: 'ph-fullstack',
    source: 'api',
    title: 'Full Stack Developer',
    company: 'Manila Cloud',
    description: `Manila Cloud is hiring a Full Stack Developer to ship product with a small remote team.

About the role
You will own features from the API through the React client. The work is full-time and remote from the Philippines. You will work in TypeScript across Next.js, Node.js, and PostgreSQL.

What you will do
• Design and ship product features end to end
• Write typed APIs and data models in Node.js and PostgreSQL
• Build and maintain the Next.js / React client
• Review code, catch regressions, and keep releases small
• Work with design and product on scope before you write the first line

What we look for
• 5+ years building production web software
• Strong React, Next.js, and TypeScript
• Node.js services and PostgreSQL in real products
• Comfortable owning a feature without a large staff around you
• Clear written English for a remote team

How to apply
Open the official listing and submit there. Atelier prepares your packet — we do not submit on other boards for you.`,
    location: 'Philippines — Remote',
    remote: true,
    workMode: 'remote',
    employmentType: 'full-time',
    salaryMin: 48000,
    salaryMax: 84000,
    currency: 'USD',
    skills: ['React', 'Next.js', 'TypeScript', 'Node.js', 'PostgreSQL'],
    requiredExperience: 5,
    seniority: 'senior',
    applicationUrl: 'https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Developer%20Manila%20Cloud',
    applyChannel: 'Open listing — submit on official boards',
    postedAt: '2026-09-03',
  },
]
